[2021-07-08 17:19:55,674] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: bluepi_dag.dump_user_log 2021-07-08T17:19:46.066642+00:00 [queued]>
[2021-07-08 17:19:55,691] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: bluepi_dag.dump_user_log 2021-07-08T17:19:46.066642+00:00 [queued]>
[2021-07-08 17:19:55,692] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2021-07-08 17:19:55,692] {taskinstance.py:1088} INFO - Starting attempt 1 of 1
[2021-07-08 17:19:55,692] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2021-07-08 17:19:55,699] {taskinstance.py:1107} INFO - Executing <Task(PythonOperator): dump_user_log> on 2021-07-08T17:19:46.066642+00:00
[2021-07-08 17:19:55,704] {standard_task_runner.py:52} INFO - Started process 366 to run task
[2021-07-08 17:19:55,711] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'bluepi_dag', 'dump_user_log', '2021-07-08T17:19:46.066642+00:00', '--job-id', '209', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/bluepi_dag.py', '--cfg-path', '/tmp/tmpd_m5qppq', '--error-file', '/tmp/tmp6oqtzbe5']
[2021-07-08 17:19:55,717] {standard_task_runner.py:77} INFO - Job 209: Subtask dump_user_log
[2021-07-08 17:19:55,776] {logging_mixin.py:104} INFO - Running <TaskInstance: bluepi_dag.dump_user_log 2021-07-08T17:19:46.066642+00:00 [running]> on host 3cf0296804bd
[2021-07-08 17:19:55,842] {taskinstance.py:1302} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=natchanon
AIRFLOW_CTX_DAG_ID=bluepi_dag
AIRFLOW_CTX_TASK_ID=dump_user_log
AIRFLOW_CTX_EXECUTION_DATE=2021-07-08T17:19:46.066642+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-07-08T17:19:46.066642+00:00
[2021-07-08 17:19:55,854] {base.py:78} INFO - Using connection to: id: my_postgres_conn. Host: 35.247.174.171, Port: 5432, Schema: postgres, Login: exam, Password: ***, extra: {}
[2021-07-08 17:19:57,611] {python.py:151} INFO - Done. Returned value was: None
[2021-07-08 17:19:57,622] {taskinstance.py:1211} INFO - Marking task as SUCCESS. dag_id=bluepi_dag, task_id=dump_user_log, execution_date=20210708T171946, start_date=20210708T171955, end_date=20210708T171957
[2021-07-08 17:19:57,664] {taskinstance.py:1265} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-07-08 17:19:57,690] {local_task_job.py:151} INFO - Task exited with return code 0
